<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_uncategorised</name>
   <tag></tag>
   <elementGuidId>c9728b37-597c-4646-ae4a-7c5c919ba032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'uncategorised')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4185df95-dcb2-4ded-abd4-fd81965af6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge bg-light text-navy fw-light fs-6 text-decoration-none</value>
      <webElementGuid>93fda5cf-9d7f-4a95-a2e2-af74115de532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categories/category/uncategorised/</value>
      <webElementGuid>bdb6ab83-a86f-4f90-9ed3-43d6c0607a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>uncategorised</value>
      <webElementGuid>a5cc088c-31bb-4028-979e-155814f78b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;bg-navy text-white&quot;]/div[@class=&quot;container home-posts&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4&quot;]/div[@class=&quot;card mb-4 bg-navy border-grey-60&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-auto mb-3&quot;]/a[@class=&quot;badge bg-light text-navy fw-light fs-6 text-decoration-none&quot;]</value>
      <webElementGuid>3bdf782b-abfe-418c-ab6f-dc4ff03618b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'uncategorised')]</value>
      <webElementGuid>dc54667d-e57e-420c-97cf-f751593b6a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='travel'])[1]/following::a[1]</value>
      <webElementGuid>6172352a-adc3-4238-aa9b-b09100f0e7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='random'])[1]/following::a[2]</value>
      <webElementGuid>800e4ed5-858a-49eb-b9df-b2fa7c55c6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='friends'])[1]/preceding::a[1]</value>
      <webElementGuid>6b49a573-3ff7-422d-a45b-77dd6131f552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='uncategorised']/parent::*</value>
      <webElementGuid>f61118cc-1a0c-4830-8c3b-76fe9ebe0eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/categories/category/uncategorised/')]</value>
      <webElementGuid>05aab092-6808-4720-be5e-48f603060eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>f6d3870a-9dfb-44c6-962b-f5133149076c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/categories/category/uncategorised/' and (text() = 'uncategorised' or . = 'uncategorised')]</value>
      <webElementGuid>64b42f86-df5d-4a9f-998f-b443fe80e1ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
