<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments_body</name>
   <tag></tag>
   <elementGuidId>994154be-ab2d-4f44-a0a3-7dd411df72d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='id_body']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>df8c327f-27e6-4b7d-9ab7-4e4f74f0495c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>00158a73-5880-4243-850f-1cbf19905a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c44d56a2-760e-4a72-a829-de789b32ef16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b01bff6a-da90-470e-8a13-4ed657411e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add a comment</value>
      <webElementGuid>b3259bb4-011e-4779-b3a1-77843fe97f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea form-control</value>
      <webElementGuid>ef600f83-b8e3-478d-9da1-20cf1e8c3e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_body</value>
      <webElementGuid>237d1709-49e1-4fb5-9802-3ebb0fd79d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_body&quot;)</value>
      <webElementGuid>f0fe3d12-47ad-44f6-b0b3-83c87cf56684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='id_body']</value>
      <webElementGuid>d1fd3890-eef4-4f53-83a5-26e5f48f3ecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_body']/textarea</value>
      <webElementGuid>4f7d2c4f-e5d2-4f22-8e00-e3ac7768d6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d6184796-cec7-4c0d-8b99-31f9bd416abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'body' and @placeholder = 'Add a comment' and @id = 'id_body']</value>
      <webElementGuid>13cd4edb-0509-478c-acc4-ad343e11a505</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
