<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_drinks</name>
   <tag></tag>
   <elementGuidId>61d245f8-dfd0-48e2-a870-43bd35e92585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.badge.bg-light.text-decoration-none.link-dark.fs-6.fw-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'drinks')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c516d10-917a-4887-9568-d1c1da283f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge bg-light text-decoration-none link-dark fs-6 fw-light</value>
      <webElementGuid>f0ebe14b-b216-4eec-a857-7729d4753978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categories/category/drinks/</value>
      <webElementGuid>96c0ba70-cc8c-40a7-a805-a0a7943ba7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>drinks</value>
      <webElementGuid>0d97077a-9d6d-4409-ad74-0e18ff88f14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;bg-navy text-white&quot;]/div[@class=&quot;container mt-5&quot;]/div[@class=&quot;row d-flex flex-column align-items-center&quot;]/div[@class=&quot;col-lg-8&quot;]/section[@class=&quot;mb-5&quot;]/a[@class=&quot;badge bg-light text-decoration-none link-dark fs-6 fw-light&quot;]</value>
      <webElementGuid>ae41f939-abc0-4691-9696-3a1f2eb7f8db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'drinks')]</value>
      <webElementGuid>44c0b2c6-f5cb-426d-8426-08897b01b3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[2]/following::a[1]</value>
      <webElementGuid>7e79ef76-0d54-481f-85ff-0869627b6de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='drinks']/parent::*</value>
      <webElementGuid>0b14f3ae-6b6d-4319-8029-d998395cb5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/categories/category/drinks/')]</value>
      <webElementGuid>cde6802b-5dfd-4faf-a0a0-65762fb98737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/a</value>
      <webElementGuid>b8220f5a-105b-448a-9c2c-a12602daf361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/categories/category/drinks/' and (text() = 'drinks' or . = 'drinks')]</value>
      <webElementGuid>c10e1bc1-f087-4d85-bb09-fdd2536520dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
