<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password1</name>
   <tag></tag>
   <elementGuidId>1a1a50cc-a78d-4919-bc5a-8186e39ffefd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_password1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_password1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e85e8c5-d9b0-41ac-abd9-9af891af424f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8de84e5e-b7d9-4dc2-9e23-d2158cf1dff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password1</value>
      <webElementGuid>6faef594-0d9b-44c7-8959-8c463d9d6f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>447e1aa8-20ff-44b2-ad1f-1d8e829adb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput textInput form-control</value>
      <webElementGuid>c27f1909-201f-4eea-a713-ea50893e87ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_password1</value>
      <webElementGuid>631b88ca-3802-431b-8a17-81578236bc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>4a942d74-46c1-4586-911f-fd9ceecc82e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_password1&quot;)</value>
      <webElementGuid>58ba7396-ccd8-41e2-b585-ed47d9ca635e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_password1']</value>
      <webElementGuid>fbdc78de-44a5-4aa9-9cb6-037dbdcf4fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_password1']/input</value>
      <webElementGuid>feff4747-c6ab-438a-8ab3-3269fc42bed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6077471d-c8e3-43c6-8031-48b363feda1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password1' and @placeholder = 'Password' and @id = 'id_password1']</value>
      <webElementGuid>09e1afda-3ca7-4d99-8304-48008dd9b940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
