# Generated by Django 3.2 on 2022-05-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_dislikes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
