<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>3619c46d-c17a-4ea7-b979-9b7a6cdd9506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-outline-coral</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Login')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d519499-4612-4aa5-98f5-18077abec4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-coral</value>
      <webElementGuid>bfd8da69-1fdb-4137-9ed9-f6fde5810bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/owlet/login/</value>
      <webElementGuid>bd0feecb-70d0-4744-918b-b392e25eb86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b76926e-75c8-44ca-81b6-c530b85e9a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>72b92138-5379-43e0-a13a-65e2d3a0003e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;bg-navy text-white&quot;]/nav[@class=&quot;navbar navbar-expand-sm navbar-dark bg-navy&quot;]/div[@class=&quot;container-lg&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item d-none d-sm-block me-2&quot;]/a[@class=&quot;btn btn-outline-coral&quot;]</value>
      <webElementGuid>7a4fc998-ef1f-4cb1-a125-f0f40ff47d59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>5112a582-7a3e-47f0-91ba-03c0c2f675b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/preceding::a[1]</value>
      <webElementGuid>d4cc2799-613b-4e06-a65d-0b503890b8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get started'])[1]/preceding::a[2]</value>
      <webElementGuid>2c41a31a-8718-4432-9a53-f4832af47ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>cce2b476-6cf4-4550-b400-ee6cd2a7b337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/owlet/login/')]</value>
      <webElementGuid>db19f0e0-0cb2-4241-8a5b-a4b7c20c96d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>15a525fd-0c43-41bc-b5c9-499e8696601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/owlet/login/' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>6b3e1222-b35c-404b-a07e-f47fee7b6c49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
