<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Paragraph_id_content_ifr</name>
   <tag></tag>
   <elementGuidId>142ad545-d35c-4baa-ad0f-f6ab65f281cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_content_ifr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='id_content_ifr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d1147978-1597-45fb-b803-78d615e72140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_content_ifr</value>
      <webElementGuid>1b148870-3d88-4be8-a1e4-52e699f969b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2cd654b0-a8ff-4e39-a720-07bae9f6d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>baa1aefb-8a86-4e61-a386-4597278027cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich Text Area</value>
      <webElementGuid>535f2817-3bf9-4ced-995d-f5b2a7e4e52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tox-edit-area__iframe</value>
      <webElementGuid>c58a4b27-b361-4911-86d2-285fa2b1f0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcdoc</name>
      <type>Main</type>
      <value>&lt;!DOCTYPE html>&lt;html>&lt;head>&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; />&lt;/head>&lt;body id=&quot;tinymce&quot; class=&quot;mce-content-body &quot; data-id=&quot;id_content&quot; aria-label=&quot;Rich Text Area. Press ALT-0 for help.&quot;>&lt;br>&lt;/body>&lt;/html></value>
      <webElementGuid>1f7368ba-a872-49c6-bc1f-cd13a24df56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_content_ifr&quot;)</value>
      <webElementGuid>10332b0e-b0bf-4985-959a-485a9bdefc27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='id_content_ifr']</value>
      <webElementGuid>2a19b297-acb8-47c0-9824-998ffa6da067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_content']/div/div/div[2]/div/iframe</value>
      <webElementGuid>b93c5f68-01f7-46b3-9168-396ce049d460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c7186acb-87b7-4f2a-ba13-1442ff11143f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'id_content_ifr' and @title = 'Rich Text Area']</value>
      <webElementGuid>f2acf9d1-5572-47e1-a96c-78c885465379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
