<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__excerpt</name>
   <tag></tag>
   <elementGuidId>70f74a63-018a-48ec-8463-e521b4697033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_excerpt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_excerpt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce73f1e0-74e1-48f4-a62d-369764d4ec66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d33be6b-9adf-4d46-829a-e61f5820d1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>excerpt</value>
      <webElementGuid>a5599182-e0e2-48d3-85e5-b36c17193fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>3b84d29e-2442-423e-95e9-f45a73a855f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput textInput form-control</value>
      <webElementGuid>03e95965-fa0d-41f8-96f4-c0befc56e917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_excerpt</value>
      <webElementGuid>a2262766-b40b-45d7-9921-9cb02f3b2eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_excerpt&quot;)</value>
      <webElementGuid>6799fbf4-b5a4-44a8-809e-e9d498e539ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_excerpt']</value>
      <webElementGuid>92d7f90d-cfa7-469b-b96a-3ed4469c7519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_excerpt']/input</value>
      <webElementGuid>171477aa-b466-497d-9ce7-5a50ac14497d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>9e49465b-ee42-4ea4-9b5a-fb56413157ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'excerpt' and @id = 'id_excerpt']</value>
      <webElementGuid>5450f278-3b0b-4aa0-9253-af349599adba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
