<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--------- random travel drinks uncat_857b50</name>
   <tag></tag>
   <elementGuidId>e107553c-d89a-4737-80b3-f6f7135eed44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_category']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ab2774e-251f-431a-86b6-811ba059cb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>category</value>
      <webElementGuid>30fb3d5d-e893-4dc1-aeb4-501661ac111c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select form-select</value>
      <webElementGuid>394e526a-d47b-4d61-97cd-f0e0bb56c6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_category</value>
      <webElementGuid>6146529f-4eee-4a97-a1e3-4d1c017a8316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --------- random travel drinks uncategorised friends

</value>
      <webElementGuid>f931b071-03e7-4968-9143-2eccd92cd36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_category&quot;)</value>
      <webElementGuid>f73bd7f6-7dd4-46b7-9b06-96013756d7a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_category']</value>
      <webElementGuid>949b042d-efcd-4713-ae55-25b403e62716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_category']/select</value>
      <webElementGuid>e82640ac-659e-4137-bde7-cfee1a9383f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::select[1]</value>
      <webElementGuid>c2d767fc-3242-4e4e-be46-85606da51044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>c159551e-e185-43e4-961e-6b0f0b20d9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add category'])[1]/preceding::select[1]</value>
      <webElementGuid>e8c4e646-d101-48ff-9ff1-d110ef35fb19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ae70266f-0d95-4c53-be0c-40ba2c8fe9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'category' and @id = 'id_category' and (text() = ' --------- random travel drinks uncategorised friends

' or . = ' --------- random travel drinks uncategorised friends

')]</value>
      <webElementGuid>fc0f9950-d69b-499b-8f80-5736120443de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
